### ISSUE TITLE
Dataset download link is unavailable

### ISSUE THREAD

**Issue by JEILDLWLRMA** [tuyunbin/SCORER#10]
I don't think the dataset download link you provided is available. Can you provide a new link?

**Comment by tuyunbin** [comment]
Thank you for pointing out this problem. I notice that the original google drive link provided by DUDA [ICCV'19] is not accessible, so I provide a baidu drive link here: https://pan.baidu.com/s/1PiLlUw5PP7IzWP_OH400AQ. The extraction code is qtzy.

**Comment by JEILDLWLRMA** [comment]
Thank you for your work :)
