### ISSUE TITLE
Could you post transformer_vocab.json and transformer_labels.h5 files?

### ISSUE THREAD

**Issue by wenting666** [tuyunbin/SCORER#9]
FileNotFoundError: [Errno 2] No such file or directory: './data/transformer_vocab.json'

**Comment by tuyunbin** [comment]
Hi, you can obtain these files by this command:

Build vocab and label files using caption annotations:

python scripts/preprocess_captions_transformer.py --input_captions_json ./data/change_captions.json --input_neg_captions_json ./data/no_change_captions.json --input_image_dir ./data/images --split_json ./data/splits.json --output_vocab_json ./data/transformer_vocab.json --output_h5 ./data/transformer_labels.h5
